const ACADEMY_VERSION='6.0.0';
const ACADEMY_KEY='udt_academy_v1';
let academyData=loadAcademyData();
let academyGame=null,academyTechIndex=0,academyExam=null;
function loadAcademyData(){try{return Object.assign({xp:0,games:{played:0,correct:0},tech:{},notes:{},favorites:[],history:[],days:{}},JSON.parse(localStorage.getItem(ACADEMY_KEY)||'{}'))}catch(_){return {xp:0,games:{played:0,correct:0},tech:{},notes:{},favorites:[],history:[],days:{}}}}
function saveAcademy(){academyData.days[new Date().toISOString().slice(0,10)]=1;localStorage.setItem(ACADEMY_KEY,JSON.stringify(academyData))}
function academySupported(){return activeMachine==='excavators'||activeMachine==='backhoes'}
function academyTechTasks(){return TECHNOLOGY_TASKS[activeMachine]||[]}
function academyAllTasks(){return [...oralTasks().map(t=>({...t,kind:'oral',technical:t.prompt,human:t.answer,errors:[t.trap],criteria:t.steps})),...academyTechTasks().map(t=>({...t,kind:'tech',prompt:t.technical,answer:t.human,trap:t.errors[0]}))]}
function hideForAcademy(){['setup','dashboard','machinePicker','quiz','result','stats','browser','questionDetail','diagnostics','achievements','oralTrainer'].forEach(id=>document.getElementById(id)?.classList.add('hidden'))}
function showAcademy(){if(!academySupported()){alert('Akademia jest dostępna dla koparki kl. I i koparkoładowarki kl. III.');return}hideForAcademy();document.getElementById('academy').classList.remove('hidden');renderAcademyHub();window.scrollTo({top:0})}
function closeAcademy(){document.getElementById('academy').classList.add('hidden');backToMenu()}
function academyRoot(){return document.getElementById('academyBody')}
function renderAcademyHub(){const tech=academyTechTasks().length,oral=oralTasks().length;academyRoot().innerHTML=`
<div class="academy-hero"><div><span>WERSJA ${ACADEMY_VERSION}</span><h1>🎓 Akademia Operatora</h1><p>${MACHINE_META[activeMachine].name} • ${oral} zadań obsługowych • ${tech} zadań technologicznych</p></div><div class="academy-level"><b>${academyData.xp||0} XP</b><span>${academyRank()}</span></div></div>
<div class="academy-grid">
${academyModuleCard('🎙️','1. Egzamin obsługowy','Odpowiedzi głosowe, analiza, SRS i pytania komisji','showOralSetup()')}
${academyModuleCard('🚜','2. Zadania technologiczne','Technicznie, po ludzku, kroki, błędy i dopytania','showTechnologyModule()')}
${academyModuleCard('🎮','3. Gry proceduralne','Klikaj kroki w kolejności, uzupełniaj i wykrywaj błędy','showAcademyGames()')}
${academyModuleCard('🤖','4. Mentor','Wskazuje słabe działy i układa dzisiejszy trening','showAcademyMentor()')}
${academyModuleCard('📈','5. Statystyki','Postęp teorii, obsługi, technologii i gier w jednym miejscu','showAcademyStats()')}
${academyModuleCard('🏆','6. Osiągnięcia','Od pierwszej procedury do egzaminatora','showAcademyAchievements()')}
${academyModuleCard('🎓','7. Egzamin 1:1','Obsługa + technologia + trzy dopytania, bez podpowiedzi','startAcademyExam()')}
</div>`}
function academyModuleCard(icon,title,text,action){return `<button class="academy-module" onclick="${action}"><span>${icon}</span><div><b>${title}</b><small>${text}</small></div><i>›</i></button>`}
function academyBack(){renderAcademyHub();window.scrollTo({top:0,behavior:'smooth'})}
function academyRank(){const x=academyData.xp||0;return x>=2500?'Egzaminator':x>=1500?'Instruktor':x>=900?'Mistrz':x>=500?'Brygadzista':x>=200?'Operator III':x>=60?'Operator II':'Operator I'}
function academyNav(title){return `<div class="toolbar academy-toolbar"><div><button class="secondary" onclick="academyBack()">← Akademia</button><h2>${title}</h2></div><b>${academyData.xp||0} XP</b></div>`}
function techStat(t){return academyData.tech[t.id]||(academyData.tech[t.id]={attempts:0,score:0,status:'practice'})}
function showTechnologyModule(index=0){academyTechIndex=Math.max(0,Math.min(index,academyTechTasks().length-1));renderTechnologyTask()}
function renderTechnologyTask(){const tasks=academyTechTasks(),t=tasks[academyTechIndex],s=techStat(t);academyRoot().innerHTML=academyNav('🚜 Zadania technologiczne')+`
<div class="tech-head"><span class="pill">Zadanie ${academyTechIndex+1}/${tasks.length}</span><span class="oral-status-badge ${s.status==='known'?'known':s.status==='repeat'?'repeat':'practice'}">${s.status==='known'?'🟢 Umiem':s.status==='repeat'?'🔴 Do powtórki':'🟡 Ćwiczę'}</span></div>
<div class="tech-card technical"><b>📘 POLECENIE TECHNICZNE</b><h2>${escA(t.title)}</h2><p>${escA(t.technical)}</p></div>
<div class="tech-card human"><b>🙂 PO LUDZKU</b><p>${escA(t.human)}</p></div>
<div class="tech-tabs"><button onclick="showTechPanel('steps')">📋 Schemat</button><button class="secondary" onclick="showTechPanel('errors')">❌ Błędy</button><button class="secondary" onclick="showTechPanel('criteria')">⭐ Ocena</button><button class="secondary" onclick="showTechPanel('questions')">🎭 Dopytania</button></div>
<div id="techPanel"></div>
<div class="note-box"><b>📝 Moja notatka</b><textarea id="techNote" placeholder="Np. wskazówka instruktora...">${escA(academyData.notes[t.id]||'')}</textarea><div class="row"><button onclick="saveTechNote()">Zapisz</button><button class="secondary" onclick="toggleTechFavorite()">${academyData.favorites.includes(t.id)?'★ Ulubione':'☆ Dodaj do ulubionych'}</button></div></div>
<div class="tech-status-row"><button onclick="setTechStatus('known')">🟢 Umiem</button><button class="secondary" onclick="setTechStatus('practice')">🟡 Ćwiczę</button><button class="danger" onclick="setTechStatus('repeat')">🔴 Powtórka</button></div>
<div class="academy-pager"><button class="secondary" onclick="showTechnologyModule(${academyTechIndex-1})" ${academyTechIndex===0?'disabled':''}>← Poprzednie</button><button onclick="showTechnologyModule(${academyTechIndex+1})" ${academyTechIndex===tasks.length-1?'disabled':''}>Następne →</button></div>`;showTechPanel('steps')}
function showTechPanel(type){const t=academyTechTasks()[academyTechIndex],root=document.getElementById('techPanel');if(type==='steps')root.innerHTML=`<div class="tech-panel"><h3>Co robisz po kolei?</h3><ol>${t.steps.map(x=>`<li>${escA(x)}</li>`).join('')}</ol></div>`;if(type==='errors')root.innerHTML=`<div class="tech-panel danger-panel"><h3>Najczęstsze błędy</h3><ul>${t.errors.map(x=>`<li>${escA(x)}</li>`).join('')}</ul></div>`;if(type==='criteria')root.innerHTML=`<div class="tech-panel"><h3>Co musi być widoczne w wykonaniu?</h3>${t.criteria.map(x=>`<label class="checkline"><input type="checkbox"> ${escA(x)}</label>`).join('')}</div>`;if(type==='questions')root.innerHTML=`<div class="tech-panel"><h3>Możliwe pytania komisji</h3>${t.followups.map((x,i)=>`<div class="follow-card"><b>${i+1}.</b> ${escA(x)}</div>`).join('')}</div>`}
function saveTechNote(){const t=academyTechTasks()[academyTechIndex],v=document.getElementById('techNote').value.trim();if(v)academyData.notes[t.id]=v;else delete academyData.notes[t.id];saveAcademy();toastA('Notatka zapisana')}
function toggleTechFavorite(){const id=academyTechTasks()[academyTechIndex].id,i=academyData.favorites.indexOf(id);if(i>=0)academyData.favorites.splice(i,1);else academyData.favorites.push(id);saveAcademy();renderTechnologyTask()}
function setTechStatus(status){const s=techStat(academyTechTasks()[academyTechIndex]);s.status=status;s.attempts++;academyData.xp+=status==='known'?12:status==='repeat'?2:5;saveAcademy();renderTechnologyTask()}
function showAcademyGames(){academyRoot().innerHTML=academyNav('🎮 Gry proceduralne')+`<div class="game-menu">${academyModuleCard('🔢','Ułóż kolejność klikaniem','Klikasz kafelki, a one same wskakują jako krok 1, 2, 3…',"startSequenceGame()")}${academyModuleCard('🧩','Brakujący krok','Wybierz element wycięty z procedury',"startMissingGame()")}${academyModuleCard('🚫','Znajdź błąd','Jedna czynność jest niebezpieczna albo nielogiczna',"startErrorGame()")}${academyModuleCard('⚡','Sprint','10 szybkich rund z różnych procedur',"startSprintGame()")}</div>`}
function pickGameTask(min=4){const a=academyAllTasks().filter(t=>(t.steps||[]).length>=min);return a[Math.floor(Math.random()*a.length)]}
function startSequenceGame(){const task=pickGameTask();academyGame={type:'sequence',task,chosen:[],options:shuffleOral(task.steps.map((x,i)=>({x,i}))),checked:false};renderSequenceGame()}
function renderSequenceGame(){const g=academyGame;academyRoot().innerHTML=academyNav('🔢 Ułóż kolejność klikaniem')+`<div class="game-question"><span>${g.task.kind==='tech'?'TECHNOLOGIA':'OBSŁUGA'}</span><h2>${escA(g.task.title)}</h2><p>${escA(g.task.technical||g.task.prompt)}</p></div><h3>Twoja kolejność</h3><div class="chosen-steps">${g.chosen.length?g.chosen.map((o,i)=>`<button onclick="removeSequenceStep(${i})"><b>${i+1}</b>${escA(o.x)}<small>kliknij, aby cofnąć</small></button>`).join(''):'<p class="small">Kliknij pierwszy krok poniżej.</p>'}</div><h3>Dostępne kroki</h3><div class="step-options">${g.options.filter(o=>!g.chosen.includes(o)).map(o=>`<button onclick="chooseSequenceStep(${o.i})">${escA(o.x)}</button>`).join('')}</div><div class="row game-actions"><button onclick="checkSequenceGame()" ${g.chosen.length!==g.options.length?'disabled':''}>Sprawdź</button><button class="secondary" onclick="startSequenceGame()">Nowa procedura</button><button class="secondary" onclick="showAcademyGames()">Gry</button></div><div id="gameFeedback"></div>`}
function chooseSequenceStep(originalIndex){const o=academyGame.options.find(x=>x.i===originalIndex);if(o&&!academyGame.chosen.includes(o)){academyGame.chosen.push(o);renderSequenceGame()}}
function removeSequenceStep(pos){academyGame.chosen.splice(pos,1);renderSequenceGame()}
function checkSequenceGame(){const ok=academyGame.chosen.every((o,i)=>o.i===i);recordGame(ok,ok?25:5);document.getElementById('gameFeedback').innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'✅ Perfekcyjna kolejność!':'❌ Jeszcze nie.'}</b><p>${ok?'+25 XP':'Prawidłowo: '+academyGame.task.steps.map((x,i)=>`${i+1}. ${escA(x)}`).join('<br>')}</p></div>`}
function startMissingGame(){const task=pickGameTask(),idx=Math.floor(Math.random()*task.steps.length),correct=task.steps[idx],others=academyAllTasks().flatMap(t=>t.steps||[]).filter(x=>x!==correct);academyGame={type:'missing',task,idx,correct,options:shuffleOral([correct,...shuffleOral(others).slice(0,3)])};academyRoot().innerHTML=academyNav('🧩 Brakujący krok')+`<div class="game-question"><h2>${escA(task.title)}</h2><ol>${task.steps.map((x,i)=>`<li>${i===idx?'<b>__________</b>':escA(x)}</li>`).join('')}</ol></div><div class="step-options">${academyGame.options.map((x,i)=>`<button onclick="answerMissing(${i})">${escA(x)}</button>`).join('')}</div><div id="gameFeedback"></div>`}
function answerMissing(i){const ok=academyGame.options[i]===academyGame.correct;recordGame(ok,ok?15:3);document.getElementById('gameFeedback').innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'✅ Dobrze':'❌ Nie ten krok'}</b><p>Brakowało: ${escA(academyGame.correct)}</p><button onclick="startMissingGame()">Następne</button></div>`}
function badSentence(task){let s=(task.errors?.[0]||task.trap||'Rozpocznij pracę bez sprawdzenia otoczenia.');s=s.replace(/^Nie\s+/i,'').replace(/^Brak /i,'Pomiń ');return s}
function startErrorGame(){const task=pickGameTask(),bad=badSentence(task),idx=Math.floor(Math.random()*(task.steps.length+1)),items=[...task.steps];items.splice(idx,0,bad);academyGame={type:'error',task,bad,idx,items};academyRoot().innerHTML=academyNav('🚫 Znajdź błąd')+`<div class="game-question"><h2>${escA(task.title)}</h2><p>Kliknij nieprawidłową czynność.</p></div><div class="error-options">${items.map((x,i)=>`<button onclick="answerError(${i})"><b>${i+1}</b>${escA(x)}</button>`).join('')}</div><div id="gameFeedback"></div>`}
function answerError(i){const ok=i===academyGame.idx;recordGame(ok,ok?15:3);document.getElementById('gameFeedback').innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'✅ Wykryłeś błąd':'❌ To była prawidłowa czynność'}</b><p>Błędne było: ${escA(academyGame.bad)}</p><button onclick="startErrorGame()">Następne</button></div>`}
function startSprintGame(){academyGame={type:'sprint',round:0,score:0,total:10};nextSprintRound()}
function nextSprintRound(){if(academyGame.round>=academyGame.total){academyData.xp+=academyGame.score*3;saveAcademy();academyRoot().innerHTML=academyNav('⚡ Sprint zakończony')+`<div class="exam-result"><b>${academyGame.score}/10</b><h2>${academyGame.score>=8?'Świetny refleks':'Jeszcze jedna seria i będzie lepiej'}</h2><button onclick="startSprintGame()">Jeszcze raz</button></div>`;return}academyGame.round++;const task=pickGameTask(),correct=task.steps[Math.floor(Math.random()*task.steps.length)],others=academyAllTasks().flatMap(t=>t.steps||[]).filter(x=>x!==correct);academyGame.sprintCorrect=correct;academyGame.sprintOptions=shuffleOral([correct,...shuffleOral(others).slice(0,2)]);academyRoot().innerHTML=academyNav(`⚡ Sprint ${academyGame.round}/10`)+`<div class="game-question"><h2>${escA(task.title)}</h2><p>Który krok należy do tej procedury?</p></div><div class="step-options">${academyGame.sprintOptions.map((x,i)=>`<button onclick="answerSprint(${i})">${escA(x)}</button>`).join('')}</div>`}
function answerSprint(i){const ok=academyGame.sprintOptions[i]===academyGame.sprintCorrect;if(ok)academyGame.score++;recordGame(ok,0);nextSprintRound()}
function recordGame(ok,xp){academyData.games.played++;if(ok)academyData.games.correct++;academyData.xp+=xp;saveAcademy()}
function showAcademyMentor(){const tasks=academyAllTasks(),weak=[];oralTasks().forEach(t=>{const s=state.stats[t.id]||{};if((s.wrong||0)>0||s.oralMastery==='repeat')weak.push({title:t.title,reason:`${s.wrong||0} błędów w odpowiedzi ustnej`})});academyTechTasks().forEach(t=>{const s=techStat(t);if(s.status==='repeat')weak.push({title:t.title,reason:'oznaczone do powtórki'})});const gamePct=academyData.games.played?Math.round(academyData.games.correct/academyData.games.played*100):0;academyRoot().innerHTML=academyNav('🤖 Mentor')+`<div class="mentor-card"><h2>${weak.length?'Dzisiaj nie rozdrabniaj się.':'Nie masz jeszcze wyraźnej słabości.'}</h2><p>${weak.length?'Najpierw popraw trzy najgorsze procedury, potem dopiero rób losowy trening.':'Zagraj w 5–10 rund, a mentor zacznie wyciągać sensowne wnioski.'}</p></div><div class="mentor-plan"><h3>Plan na dziś</h3>${weak.slice(0,3).map((x,i)=>`<div><b>${i+1}. ${escA(x.title)}</b><span>${escA(x.reason)}</span></div>`).join('')||'<div><b>1. Ułóż 5 procedur</b><span>Zbuduj pierwsze dane do analizy.</span></div>'}<div><b>${weak.length+1}. Sprint proceduralny</b><span>Obecna skuteczność gier: ${gamePct}%.</span></div></div><div class="row"><button onclick="showAcademyGames()">Rozpocznij gry</button><button class="secondary" onclick="showOralSetup()">Trening ustny</button></div>`}
function showAcademyStats(){const oral=oralTasks(),oralSeen=oral.filter(t=>(state.stats[t.id]?.attempts||0)>0).length,known=oral.filter(t=>state.stats[t.id]?.oralMastery==='known').length,tech=academyTechTasks(),techKnown=tech.filter(t=>techStat(t).status==='known').length,gp=academyData.games.played,gpct=gp?Math.round(academyData.games.correct/gp*100):0;academyRoot().innerHTML=academyNav('📈 Statystyki Akademii')+`<div class="academy-stat-grid"><div><b>${oralSeen}/${oral.length}</b><span>Obsługa przerobiona</span></div><div><b>${known}</b><span>Obsługa: umiem</span></div><div><b>${techKnown}/${tech.length}</b><span>Technologia: umiem</span></div><div><b>${gp}</b><span>Rundy gier</span></div><div><b>${gpct}%</b><span>Skuteczność gier</span></div><div><b>${academyData.xp}</b><span>XP Akademii</span></div></div><h3>Historia egzaminów 1:1</h3>${academyData.history.length?academyData.history.slice().reverse().slice(0,10).map(h=>`<div class="history-item"><span>${new Date(h.date).toLocaleString('pl-PL')}</span><b>${h.score}% ${h.pass?'✅':'❌'}</b></div>`).join(''):'<p class="small">Brak ukończonych symulacji.</p>'}`}
const ACADEMY_BADGES=[['firstgame','🎮','Pierwsza gra',()=>academyData.games.played>=1],['sequence10','🔢','Układacz',()=>academyData.games.correct>=10],['techmaster','🚜','Technolog',()=>academyTechTasks().every(t=>techStat(t).status==='known')],['oralhalf','🎙️','Mówca',()=>oralTasks().filter(t=>state.stats[t.id]?.oralMastery==='known').length>=Math.ceil(oralTasks().length/2)],['exam','🎓','Zdany na próbę',()=>academyData.history.some(h=>h.pass)],['xp500','🔥','500 XP',()=>academyData.xp>=500],['perfect','💯','Perfekcyjny egzamin',()=>academyData.history.some(h=>h.score>=95)]];
function showAcademyAchievements(){const unlocked=ACADEMY_BADGES.filter(x=>x[3]()).length;academyRoot().innerHTML=academyNav('🏆 Osiągnięcia')+`<p class="small">Odblokowano ${unlocked}/${ACADEMY_BADGES.length}</p><div class="badge-grid academy-badges">${ACADEMY_BADGES.map(x=>`<div class="badge ${x[3]()?'unlocked':'locked'}"><span>${x[1]}</span><b>${x[2]}</b><small>${x[3]()?'Odblokowane':'Jeszcze nie'}</small></div>`).join('')}</div>`}
function startAcademyExam(){const oral=oralTasks()[Math.floor(Math.random()*oralTasks().length)],tech=academyTechTasks()[Math.floor(Math.random()*academyTechTasks().length)];academyExam={oral,tech,stage:1,oralScore:0,techScore:0,followups:oral.steps.slice(0,3),answers:[]};renderAcademyExam()}
function renderAcademyExam(){const e=academyExam;if(e.stage===1){academyRoot().innerHTML=academyNav('🎓 Egzamin 1:1 — etap 1/3')+`<div class="exam-warning">Bez wzorca i bez cofania. Odpowiedz tak, jak przed komisją.</div><div class="game-question"><span>ZADANIE OBSŁUGOWE</span><h2>${escA(e.oral.title)}</h2><p>${escA(e.oral.prompt)}</p></div><textarea id="academyExamAnswer" class="oral-transcript" placeholder="Powiedz odpowiedź na głos i wpisz/transkrybuj tutaj..."></textarea><button onclick="submitAcademyOral()">Zatwierdź odpowiedź</button>`}else if(e.stage===2){academyRoot().innerHTML=academyNav('🎓 Egzamin 1:1 — etap 2/3')+`<div class="game-question"><span>ZADANIE TECHNOLOGICZNE</span><h2>${escA(e.tech.title)}</h2><p>${escA(e.tech.technical)}</p></div><textarea id="academyExamAnswer" class="oral-transcript" placeholder="Opisz kolejność wykonania i zasady bezpieczeństwa..."></textarea><button onclick="submitAcademyTech()">Zatwierdź plan</button>`}else if(e.stage===3){academyRoot().innerHTML=academyNav('🎓 Egzamin 1:1 — etap 3/3')+`<div class="game-question"><span>PYTANIA UZUPEŁNIAJĄCE</span><h2>Komisja dopytuje</h2>${e.followups.map((q,i)=>`<label class="exam-follow"><b>${i+1}. ${escA(q)}</b><textarea id="examFollow${i}" placeholder="Odpowiedź..."></textarea></label>`).join('')}</div><button onclick="finishAcademyExam()">Zakończ egzamin</button>`}}
function textScore(text,items){const n=oralNorm(text),hits=items.filter(x=>oralCriterionKeywords(x).some(k=>oralKeywordHit(n,k))).length;return Math.round(hits/Math.max(1,items.length)*100)}
function submitAcademyOral(){const a=document.getElementById('academyExamAnswer').value.trim();if(a.length<5)return toastA('Odpowiedź jest za krótka');academyExam.oralScore=analyzeOralAnswer(academyExam.oral,a).score;academyExam.stage=2;renderAcademyExam()}
function submitAcademyTech(){const a=document.getElementById('academyExamAnswer').value.trim();if(a.length<5)return toastA('Plan jest za krótki');academyExam.techScore=textScore(a,[...academyExam.tech.steps,...academyExam.tech.criteria]);academyExam.stage=3;renderAcademyExam()}
function finishAcademyExam(){let f=0;academyExam.followups.forEach((q,i)=>{const a=document.getElementById('examFollow'+i).value;f+=a.trim().length>=12?1:0});const followScore=Math.round(f/academyExam.followups.length*100),score=Math.round(academyExam.oralScore*.4+academyExam.techScore*.45+followScore*.15),pass=academyExam.oralScore>=60&&academyExam.techScore>=60&&score>=70;academyData.history.push({date:Date.now(),score,pass,oral:academyExam.oralScore,tech:academyExam.techScore,follow:followScore});academyData.xp+=pass?80:25;saveAcademy();academyRoot().innerHTML=academyNav('🎓 Wynik egzaminu 1:1')+`<div class="exam-result ${pass?'pass':'fail'}"><b>${score}%</b><h2>${pass?'✅ EGZAMIN ZALICZONY':'❌ JESZCZE NIE'}</h2><div class="academy-stat-grid"><div><b>${academyExam.oralScore}%</b><span>Obsługa</span></div><div><b>${academyExam.techScore}%</b><span>Technologia</span></div><div><b>${followScore}%</b><span>Dopytania</span></div></div><p>Symulacja ocenia opis procedury. Faktyczne wykonanie maszyny nadal musi ocenić instruktor na placu.</p><button onclick="startAcademyExam()">Nowy egzamin</button></div>`}
function escA(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toastA(t){let e=document.getElementById('academyToast');if(!e){e=document.createElement('div');e.id='academyToast';e.className='academy-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
