/* UDT Trainer 7.0 — dane i trening żurawi wieżowych */
(function(){
const O=(id,title,prompt,steps,answer,trap)=>({id:`oral:cranes:${id}`,title,prompt,steps,answer,trap});
ORAL_TASKS.cranes=[
O(1,'Dokumenty i dopuszczenie','Omów warunki dopuszczenia żurawia do pracy.',['Sprawdzam decyzję zezwalającą na eksploatację.','Kontroluję dziennik konserwacji, instrukcję i dokumentację stanowiskową.','Potwierdzam uprawnienia operatora oraz przeglądy.','Porównuję konfigurację żurawia z dokumentacją.','Przy brakach nie rozpoczynam pracy i zgłaszam je.'],'Przed uruchomieniem potwierdzam dopuszczenie urządzenia, dokumentację, przeglądy i zgodność konfiguracji. Brak warunku oznacza wstrzymanie pracy.','Samo uruchomienie żurawia nie potwierdza formalnego dopuszczenia.'),
O(2,'Konstrukcja i kotwienie','Wykonaj oględziny konstrukcji i zamocowania żurawia.',['Zabezpieczam urządzenie zgodnie z instrukcją.','Oglądam podstawę, kotwienie lub podwozie i wieżę.','Sprawdzam połączenia, sworznie, śruby, spoiny i zabezpieczenia.','Szukam pęknięć, odkształceń, korozji i braków.','Nieprawidłowość zgłaszam i nie dopuszczam żurawia do pracy.'],'Kontrola obejmuje podstawę, wieżę, połączenia i zabezpieczenia. Pęknięcie, odkształcenie lub brak zabezpieczenia wymaga wstrzymania pracy.','Nie naprawiam elementów konstrukcyjnych bez procedury i uprawnień.'),
O(3,'Lina nośna','Sprawdź linę nośną przed pracą.',['Unieruchamiam mechanizmy i zapewniam bezpieczny dostęp.','Oglądam dostępny odcinek liny.','Szukam pękniętych drutów, spłaszczeń, załamań, korozji i rozplecenia.','Sprawdzam ułożenie na bębnie i krążkach oraz zamocowanie końca.','Wady oceniam według instrukcji i kryteriów wycofania.'],'Sprawdzam stan, ułożenie i zamocowanie liny. Kryteria zużycia biorę z instrukcji producenta, a po przekroczeniu limitu nie pracuję.','Nie dotykam ani nie mierzę poruszającej się liny.'),
O(4,'Hak i zblocze','Skontroluj hak i zblocze hakowe.',['Opuszczam zblocze do bezpiecznej wysokości.','Sprawdzam hak pod kątem pęknięć, odkształceń i zużycia.','Kontroluję zapadkę gardzieli, obrót i oznaczenia.','Oglądam krążki, osie, osłony i ułożenie liny.','Uszkodzony element wyłączam z użytkowania i zgłaszam.'],'Hak nie może mieć pęknięć ani trwałych odkształceń, zapadka musi domykać gardziel, a lina prawidłowo leżeć w krążkach.','Zapadka nie zwiększa udźwigu haka.'),
O(5,'Próba bez obciążenia','Wykonaj próbę mechanizmów i zabezpieczeń bez ładunku.',['Ostrzegam osoby i sprawdzam wolną strefę.','Uruchamiam żuraw zgodnie z instrukcją.','Sprawdzam podnoszenie, obrót i zmianę wysięgu lub jazdę wózka.','Kontroluję hamulce, krańcówki, wskaźniki i sygnalizację bez forsowania ograniczników.','Po usterce zatrzymuję próbę, zabezpieczam żuraw i zgłaszam.'],'Próba potwierdza płynne działanie mechanizmów, hamulców i zabezpieczeń. Ograniczniki nie są roboczymi wyłącznikami.','Nie najeżdżam wielokrotnie na krańcówki i nie obchodzę zabezpieczeń.'),
O(6,'Wiatr','Omów postępowanie przy silnym lub porywistym wietrze.',['Odczytuję wiatr i obserwuję warunki.','Porównuję wartość z instrukcją konkretnego żurawia.','Uwzględniam powierzchnię ładunku, porywy i wysokość pracy.','Po przekroczeniu limitu odkładam ładunek i przerywam operację.','Ustawiam żuraw do postoju według instrukcji.'],'Decyduje limit producenta i rzeczywiste warunki, w tym porywy oraz powierzchnia ładunku. Po przekroczeniu limitu przerywam pracę.','Nie istnieje jedna uniwersalna prędkość wiatru dla wszystkich operacji.'),
O(7,'Łączność z sygnalistą','Zorganizuj pracę bez widoczności ładunku.',['Ustalam jednego sygnalistę i sposób łączności.','Potwierdzamy znaczenie sygnałów.','Wykonuję tylko jednoznaczne polecenia; STOP respektuję od każdego.','Po utracie łączności natychmiast zatrzymuję ruch.','Wznawiam po odzyskaniu łączności i potwierdzeniu strefy.'],'Przy braku widoczności pracuję z wyznaczonym sygnalistą. Niejasny sygnał lub utrata łączności oznacza STOP.','Nie zgaduję intencji sygnalisty.'),
O(8,'Dobór udźwigu','Wyjaśnij, jak sprawdzasz możliwość podniesienia.',['Ustalam masę ładunku, haka, zawiesi i osprzętu.','Określam największy promień i konfigurację.','Odczytuję udźwig z właściwej tabeli lub wykresu.','Uwzględniam ograniczenia producenta.','Przy braku danych lub zapasu nie podnoszę.'],'Porównuję całkowite obciążenie z udźwigiem dla konkretnego promienia i konfiguracji. Zawiesia oraz osprzęt też obciążają żuraw.','Udźwig maksymalny nie obowiązuje na każdym promieniu.'),
O(9,'Kołysanie ładunku','Zareaguj na rozkołysanie ładunku.',['Nie wykonuję gwałtownej kontry.','Płynnie zatrzymuję mechanizmy.','Utrzymuję ładunek z dala od ludzi i przeszkód.','Pozwalam ładunkowi się uspokoić.','Wznawiam łagodnie albo bezpiecznie odkładam ładunek.'],'Rozkołysanego ładunku nie łapię przeciwruchem. Zatrzymuję operację, chronię strefę i pozwalam mu się uspokoić.','Gwałtowna kontra zwiększa amplitudę i obciążenia dynamiczne.'),
O(10,'Ogranicznik momentu','Co robisz po zadziałaniu ogranicznika?',['Przerywam ruch zwiększający zagrożenie.','Nie obchodzę ani nie resetuję zabezpieczenia.','Wykonuję tylko dozwolony ruch zmniejszający moment.','Bezpiecznie odkładam ładunek.','Ustalam przyczynę i zgłaszam zdarzenie.'],'Ogranicznik wyznacza granicę. Wolno wykonać tylko działanie odciążające przewidziane w instrukcji; zabezpieczenia nie wolno omijać.','Nie próbuję dociągnąć ładunku po alarmie.'),
O(11,'Linia energetyczna','Omów pracę w pobliżu linii napowietrznej.',['Identyfikuję napięcie i wymaganą odległość.','Wyznaczam strefę i nadzór zgodnie z planem.','Uwzględniam wysięgnik, linę, ładunek i możliwe kołysanie.','Nie zaczynam bez spełnienia warunków organizacyjnych.','Po kontakcie ostrzegam ludzi i stosuję procedurę awaryjną.'],'Strefę oceniam dla całego układu żurawia i ładunku. Warunki oraz odległość muszą być ustalone przed pracą.','Odległości nie oceniam na oko.'),
O(12,'Podniesienie próbne','Wykonaj oderwanie ładunku od podłoża.',['Potwierdzam masę, zawieszenie i środek ciężkości.','Napinam liny powoli.','Odrywam ładunek nieznacznie.','Sprawdzam równowagę, hamulec i zawiesia.','Po pozytywnej kontroli kontynuuję podnoszenie.'],'Pierwsze centymetry są próbą równowagi, zawiesi, hamulca i braku zakleszczenia.','Nie wyrywam ładunku z podłoża i nie podnoszę od razu wysoko.'),
O(13,'Postój żurawia','Zabezpiecz żuraw po zmianie.',['Odkładam ładunek.','Ustawiam hak, wózek i wysięgnik w położeniu postojowym.','Włączam przewidziany tryb swobodnego obrotu lub inne zabezpieczenie.','Wyłączam zasilanie i zabezpieczam kabinę.','Wpisuję uwagi i zgłaszam usterki.'],'Po pracy ustawiam żuraw dokładnie według instrukcji postoju, wyłączam i zabezpieczam, a usterki zapisuję.','Nie zostawiam ładunku na haku.'),
O(14,'Awaria z ładunkiem','Omów zanik zasilania z zawieszonym ładunkiem.',['Nie improwizuję i nie zwalniam hamulca.','Ostrzegam ludzi i zabezpieczam strefę.','Informuję kierownika i służby techniczne.','Stosuję instrukcję awaryjną konkretnego żurawia.','Wznawiam po usunięciu przyczyny i dopuszczeniu urządzenia.'],'Po zaniku zasilania zabezpieczam strefę i stosuję procedurę awaryjną. Nie wolno samowolnie zwalniać hamulca.','Ręczne zwolnienie hamulca może spowodować niekontrolowane opadnięcie.'),
O(15,'Zawiesia','Co sprawdzasz przed przyjęciem ładunku na hak?',['Sprawdzam oznaczenie, DOR i stan zawiesi.','Oceniam opasanie, kąty cięgien i środek ciężkości.','Potwierdzam ochronę ostrych krawędzi.','Sprawdzam gardziel haka i brak skręcenia.','Nie podnoszę przy niepewnej masie lub zawieszeniu.'],'Zawiesia muszą być właściwe, nieuszkodzone i poprawnie założone, a masa oraz środek ciężkości znane.','DOR pojedynczego cięgna nie oznacza DOR całego układu w każdym kącie.'),
O(16,'Praca nad ludźmi','Omów trasę ładunku nad stanowiskami pracy.',['Wyznaczam strefę niebezpieczną.','Wybieram trasę omijającą ludzi i stanowiska.','Nie ruszam, gdy ktoś jest pod ładunkiem.','Na STOP zatrzymuję operację.','Wznawiam po opuszczeniu strefy.'],'Ładunku nie transportuje się nad ludźmi. Trasa musi zapewnić pustą strefę pod i wokół ładunku.','Kask nie legalizuje przebywania pod ładunkiem.')];

const T=(id,title,technical,human,steps,errors,criteria,followups)=>({id:`tech:cranes:${id}`,title,technical,human,steps,errors,criteria,followups});
TECHNOLOGY_TASKS.cranes=[
T(1,'Przeniesienie ładunku','Pobierz ładunek, przemieść go i odłóż w wyznaczonym miejscu.','Oderwij kontrolnie, przenieś spokojnie pustą trasą i dokładnie odłóż.',['Potwierdź masę, promień, zawieszenie i strefę.','Napnij liny i wykonaj niskie podniesienie próbne.','Podnieś na minimalną bezpieczną wysokość.','Wykonuj płynne ruchy bez szarpania.','Wyhamuj przed celem.','Opuść pionowo i odciąż zawiesia.'],['Brak próby.','Ruch nad ludźmi.','Gwałtowne hamowanie.','Ciągnięcie po skosie.'],['kontrola wykresu','próba','płynność','kontrola kołysania','odłożenie'],['Dlaczego robisz próbę?','Jak ograniczasz kołysanie?']),
T(2,'Ładunek niewidoczny','Wykonaj operację bez widoczności miejsca pobrania.','Pracuj z jednym sygnalistą i zatrzymaj się, gdy komunikacja przestanie być pewna.',['Ustal sygnalistę i kanał.','Potwierdź masę i pustą strefę.','Wykonuj ruchy tylko na jednoznaczne sygnały.','Po utracie łączności zatrzymaj ruch.','Wznów po potwierdzeniu warunków.'],['Domyślanie się sygnału.','Polecenia od wielu osób.','Ruch po utracie radia.'],['jeden sygnalista','łączność','reakcja STOP','strefa'],['Kto może dać STOP?','Co po utracie łączności?']),
T(3,'Ładunek podatny na wiatr','Przemieść ładunek o dużej powierzchni.','Traktuj go jak żagiel: oceń wiatr, zaplanuj prowadzenie i przerwij po utracie kontroli.',['Sprawdź limity wiatru.','Wyznacz trasę i sposób prowadzenia.','Zastosuj liny kierunkowe, jeśli przewiduje je plan.','Podnieś próbnie.','Przemieszczaj powoli.','Przerwij przy utracie kontroli.'],['Ignorowanie porywów.','Ręce w strefie zgniotu.','Gwałtowna kontra.'],['wiatr','prowadzenie','płynność','przerwanie'],['Dlaczego sama masa nie wystarcza?','Kiedy przerywasz?']),
T(4,'Granica promienia','Zaplanuj podniesienie blisko granicy dopuszczalnego promienia.','Sprawdź najgorszy punkt całej trasy, pełną masę i właściwą konfigurację.',['Ustal masę z osprzętem.','Wyznacz największy promień.','Wybierz właściwą tabelę.','Porównaj masę z udźwigiem.','Zostaw wymagany margines.','Odmów przy braku danych.'],['Sprawdzenie tylko startu.','Pominięcie zawiesi.','Planowanie do alarmu.'],['największy promień','konfiguracja','pełna masa','margines'],['Który punkt decyduje?','Czy ogranicznik zastępuje plan?']),
T(5,'Ciasne miejsce odkładania','Odłóż ładunek w ograniczonej przestrzeni.','Wygasz kołysanie, opuść pionowo i nie dopychaj hakiem.',['Potwierdź miejsce i podłoże.','Usuń ludzi ze stref zgniotu.','Podejdź minimalną prędkością.','Wygasz kołysanie.','Opuść pionowo.','Odciąż zawiesia.'],['Dopychanie hakiem.','Ręce w strefie zgniotu.','Odczepienie napiętych zawiesi.'],['strefa','pionowe opuszczanie','podłoże','odciążenie'],['Kiedy hakowy podchodzi?','Dlaczego odciążasz zawiesie?']),
T(6,'Alarm ogranicznika','Zareaguj na alarm podczas ruchu.','Zatrzymaj ruch pogarszający sytuację, zmniejsz moment dozwolonym ruchem i odłóż ładunek.',['Zatrzymaj bez szarpnięcia.','Rozpoznaj alarm.','Nie resetuj zabezpieczenia.','Wykonaj ruch odciążający.','Odłóż ładunek.','Zgłoś przyczynę.'],['Zwiększanie promienia.','Reset pod obciążeniem.','Gwałtowne opuszczenie.'],['alarm','odciążenie','odłożenie','zgłoszenie'],['Jaki ruch zwiększa moment?','Dlaczego nie resetujesz?'])];

window.CRANE_SIGNALS=[['STOP','Jedna ręka uniesiona, dłoń do przodu','Zatrzymaj wszystkie ruchy'],['STOP awaryjny','Obie ręce uniesione, dłonie do przodu','Natychmiast zatrzymaj wszystkie ruchy'],['Podnoś','Ramię w górę, palec zatacza koła','Podnoś hak lub ładunek'],['Opuszczaj','Ramię w dół, palec zatacza koła','Opuszczaj hak lub ładunek'],['Ruch powolny','Sygnał ruchu z drugą dłonią nieruchomo przed ręką sygnalizującą','Wykonuj wskazany ruch bardzo wolno'],['Kierunek ruchu','Ręka wskazuje kierunek','Przemieszczaj w pokazanym kierunku'],['Koniec operacji','Dłonie złożone na wysokości klatki','Operacja zakończona'],['Odległość','Dłonie pokazują malejącą odległość','Pozostała odległość do celu']];
window.CRANE_LOAD_CHART=[{r:12,cap:6000},{r:16,cap:4800},{r:20,cap:3800},{r:24,cap:3100},{r:28,cap:2600},{r:32,cap:2200},{r:36,cap:1900},{r:40,cap:1650},{r:44,cap:1450},{r:48,cap:1250}];
})();
