/* Interaktywne moduły Akademii Żurawia. Tabela jest ćwiczebna, nie zastępuje DTR. */
let craneLoadQuestion=null,craneSignalQuestion=null;
function craneTrainerStat(kind){academyData[kind]=academyData[kind]||{attempts:0,correct:0};return academyData[kind]}
function showCraneLoadTrainer(){if(activeMachine!=='cranes')return academyBack();const s=craneTrainerStat('loadChart');academyRoot().innerHTML=academyNav('📐 Trener wykresu udźwigu')+`<div class="exam-warning">Tabela ćwiczebna. W pracy zawsze używaj tabeli właściwej dla konkretnego żurawia i konfiguracji.</div><div class="academy-stat-grid"><div><b>${s.correct}/${s.attempts}</b><span>Poprawne</span></div><div><b>${s.attempts?Math.round(s.correct/s.attempts*100):0}%</b><span>Skuteczność</span></div></div><div id="craneLoadTask"></div>`;nextCraneLoadQuestion()}
function nextCraneLoadQuestion(){const chart=CRANE_LOAD_CHART,row=chart[Math.floor(Math.random()*chart.length)],rigging=[80,120,160,220][Math.floor(Math.random()*4)],safe=Math.random()>.45,maxCargo=Math.floor((row.cap-rigging)/50)*50,cargo=safe?Math.max(100,maxCargo-[0,50,100,200][Math.floor(Math.random()*4)]):maxCargo+[50,100,200,300][Math.floor(Math.random()*4)];craneLoadQuestion={row,rigging,cargo,total:cargo+rigging,safe:(cargo+rigging)<=row.cap};const q=craneLoadQuestion,root=document.getElementById('craneLoadTask');if(!root)return;root.innerHTML=`<div class="tech-card technical"><b>ĆWICZENIE</b><h2>Promień ${q.row.r} m</h2><p>Ładunek: <b>${q.cargo} kg</b> • zawiesia i osprzęt: <b>${q.rigging} kg</b><br>Udźwig z tabeli: <b>${q.row.cap} kg</b></p></div><div class="row"><button onclick="answerCraneLoad(true)">✅ Można podnieść</button><button class="danger" onclick="answerCraneLoad(false)">⛔ Nie można</button></div><div id="craneLoadFeedback"></div><details class="card home-more"><summary>Pokaż tabelę ćwiczebną</summary><div class="load-chart-grid">${CRANE_LOAD_CHART.map(x=>`<span>${x.r} m</span><b>${x.cap} kg</b>`).join('')}</div></details>`}
function answerCraneLoad(answer){const q=craneLoadQuestion,s=craneTrainerStat('loadChart'),ok=answer===q.safe;s.attempts++;if(ok)s.correct++;academyData.xp+=ok?12:3;saveAcademy();document.getElementById('craneLoadFeedback').innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'✅ Dobrze':'❌ Błędna decyzja'}</b><p>Całkowite obciążenie: ${q.cargo} + ${q.rigging} = <b>${q.total} kg</b>. Udźwig przy ${q.row.r} m: <b>${q.row.cap} kg</b>. ${q.safe?'Mieści się w limicie tabeli ćwiczebnej.':'Limit przekroczony o '+(q.total-q.row.cap)+' kg.'}</p><button onclick="nextCraneLoadQuestion()">Następne ćwiczenie</button></div>`}
function showCraneSignals(){if(activeMachine!=='cranes')return academyBack();const s=craneTrainerStat('signals');academyRoot().innerHTML=academyNav('🫱 Sygnały ręczne')+`<div class="exam-warning">Opis tekstowy uczy znaczeń. Na placu potwierdź zestaw sygnałów stosowany przez ośrodek.</div><div class="academy-stat-grid"><div><b>${s.correct}/${s.attempts}</b><span>Poprawne</span></div><div><b>${s.attempts?Math.round(s.correct/s.attempts*100):0}%</b><span>Skuteczność</span></div></div><div id="craneSignalTask"></div>`;nextCraneSignalQuestion()}
function nextCraneSignalQuestion(){const correct=CRANE_SIGNALS[Math.floor(Math.random()*CRANE_SIGNALS.length)],others=shuffleOral(CRANE_SIGNALS.filter(x=>x!==correct)).slice(0,3),options=shuffleOral([correct,...others]);craneSignalQuestion={correct,options};document.getElementById('craneSignalTask').innerHTML=`<div class="tech-card human"><b>CO OZNACZA TEN SYGNAŁ?</b><h2>${escA(correct[1])}</h2></div><div class="step-options">${options.map((x,i)=>`<button onclick="answerCraneSignal(${i})">${escA(x[0])}</button>`).join('')}</div><div id="craneSignalFeedback"></div>`}
function answerCraneSignal(i){const q=craneSignalQuestion,pick=q.options[i],ok=pick===q.correct,s=craneTrainerStat('signals');s.attempts++;if(ok)s.correct++;academyData.xp+=ok?10:2;saveAcademy();document.getElementById('craneSignalFeedback').innerHTML=`<div class="game-feedback ${ok?'good':'bad'}"><b>${ok?'✅ Dobrze':'❌ To jest: '+escA(q.correct[0])}</b><p>${escA(q.correct[2])}</p><button onclick="nextCraneSignalQuestion()">Następny sygnał</button></div>`}

const baseAcademyStats=window.showAcademyStats;
window.showAcademyStats=function(){if(activeMachine!=='cranes')return baseAcademyStats();const oral=oralTasks(),seen=oral.filter(t=>(state.stats[t.id]?.attempts||0)>0).length,known=oral.filter(t=>state.stats[t.id]?.oralMastery==='known').length,tech=academyTechTasks(),techKnown=tech.filter(t=>techStat(t).status==='known').length,load=craneTrainerStat('loadChart'),signals=craneTrainerStat('signals'),pct=x=>x.attempts?Math.round(x.correct/x.attempts*100):0;academyRoot().innerHTML=academyNav('📈 Statystyki Akademii Żurawia')+`<div class="academy-stat-grid"><div><b>${seen}/${oral.length}</b><span>Obsługa przerobiona</span></div><div><b>${known}</b><span>Obsługa: umiem</span></div><div><b>${techKnown}/${tech.length}</b><span>Praktyka: umiem</span></div><div><b>${pct(load)}%</b><span>Wykres udźwigu (${load.attempts})</span></div><div><b>${pct(signals)}%</b><span>Sygnały (${signals.attempts})</span></div><div><b>${academyData.xp}</b><span>XP Akademii</span></div></div>`};
const baseAcademyMentor=window.showAcademyMentor;
window.showAcademyMentor=function(){if(activeMachine!=='cranes')return baseAcademyMentor();const weak=[];oralTasks().forEach(t=>{const s=state.stats[t.id]||{};if((s.wrong||0)>0||s.oralMastery==='repeat')weak.push({title:t.title,reason:'odpowiedź ustna wymaga powtórki'})});academyTechTasks().forEach(t=>{if(techStat(t).status==='repeat')weak.push({title:t.title,reason:'scenariusz oznaczony do powtórki'})});const load=craneTrainerStat('loadChart'),signals=craneTrainerStat('signals'),lp=load.attempts?Math.round(load.correct/load.attempts*100):0,sp=signals.attempts?Math.round(signals.correct/signals.attempts*100):0;if(load.attempts<5||lp<75)weak.unshift({title:'Wykres udźwigu',reason:load.attempts<5?'za mało prób':'skuteczność '+lp+'%'});if(signals.attempts<5||sp<80)weak.unshift({title:'Sygnały ręczne',reason:signals.attempts<5?'za mało prób':'skuteczność '+sp+'%'});academyRoot().innerHTML=academyNav('🤖 Mentor żurawia')+`<div class="mentor-card"><h2>${weak.length?'Tu masz robotę na dziś.':'Nie widać obecnie wyraźnej dziury.'}</h2><p>${weak.length?'Najpierw popraw najsłabsze elementy, potem rób egzamin 1:1.':'Utrzymaj formę krótką sesją mieszaną.'}</p></div><div class="mentor-plan"><h3>Plan na dziś</h3>${weak.slice(0,4).map((x,i)=>`<div><b>${i+1}. ${escA(x.title)}</b><span>${escA(x.reason)}</span></div>`).join('')||'<div><b>1. Egzamin 1:1</b><span>Sprawdź utrzymanie wyniku.</span></div>'}</div><div class="row"><button onclick="showCraneLoadTrainer()">Wykres</button><button onclick="showCraneSignals()">Sygnały</button><button class="secondary" onclick="showOralSetup()">Ustny</button></div>`};
