const CRANE_QUESTIONS=[].concat(CRANE_QUESTIONS_PART_1,CRANE_QUESTIONS_PART_2,CRANE_QUESTIONS_PART_3,CRANE_QUESTIONS_PART_4);
const EXCAVATOR_QUESTIONS=[].concat(EXCAVATOR_QUESTIONS_PART_1);
const BACKHOE_QUESTIONS=[].concat(BACKHOE_QUESTIONS_PART_1);

const LOADER_QUESTIONS=[].concat(LOADER_QUESTIONS_PART_1);
